name = "LegendrePolynomials"
uuid = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
version = "0.3"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "0.11, 1"
julia = "1"

[extras]
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HyperDualNumbers", "Test"]
