name = "LegendrePolynomials"
uuid = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
version = "0.2.2"

[deps]
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
HyperDualNumbers = "4"
OffsetArrays = "0.11, 1.0"
julia = "1"
